import argparse


class ArgParseManager(object):
    # Just to keep the methods here out of the global namespace

    def _create_full_argparser(self):
        parser = argparse.ArgumentParser()

        subparsers =  parser.add_subparsers()

        config_parser = subparsers.add_parser("--config")
        self._populate_config_mode_parser(config_parser)


    def _populate_config_mode_parser(self, config_parser):
        config_parser.add_argument("config_file_path", "The full path to the JSON file containing the experiment "
                                                       "configs.")
        config_parser.add_argument("--output-dir", "The output directory where logs and models for all experiments "
                                                   "generated by this config file are stored.")

    @classmethod
    def parse(self):
        argparser = ArgParseManager()._create_full_argparser()
        args = argparser.parse()

        return args


if __name__ == "__main__":
    ArgParseManager.parse()
