
name: Python package

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v2
      with:
        activate-environment: venv_continual_rl
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}  # Activates the conda environment just created
      run: |
        pip install .
        pip install -r tests/requirements.txt
    - name: Shell info
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=W291
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        which pytest
        pytest
